ALTER TABLE users ADD COLUMN IF NOT EXISTS signature_path TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS registration_number VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS designation VARCHAR(255);
